### ISSUE TITLE
Updating Lab Activity 1

### ISSUE THREAD

**Issue by Macro303** [AndreaWolff/Project-JAJA#1]
This is both a testing of issues and as information to add to the lab activity. The information that i think should be added is that Andrew said he would take some screenshots of him doing the git username and email, they might be useful with the other screenshots of installing git.

**Comment by ShinyChrome** [comment]
![dsc_0820 swp hi res](https://cloud.githubusercontent.com/assets/13409402/8900747/f8bb48b0-3496-11e5-8fac-03c2a8f0b9d6.jpg)

Howdy, Its fine. I did the stuff and things
